version: '3.8' services: frontend: build: 
      context: ./frontend dockerfile: 
      Dockerfile
    ports: - "80:80" depends_on: - backend 
    environment:
      - 
      VITE_API_BASE_URL=http://localhost:5000/api
    restart: unless-stopped backend: build: 
      context: ./backend dockerfile: 
      Dockerfile
    ports: - "5000:5000" depends_on: - 
      mongodb
    environment: - NODE_ENV=production - 
      PORT=5000 - 
      MONGO_URI=mongodb://mongodb:27017/webscraper 
      - JWT_SECRET=your_jwt_secret - 
      JWT_EXPIRES_IN=7d - 
      CORS_ORIGIN=http://localhost,http://localhost:80,https://yourdomain.com
    restart: unless-stopped mongodb: image: 
    mongo:5 ports:
      - "27017:27017" volumes: - 
      mongodb_data:/data/db
    restart: unless-stopped volumes: 
  mongodb_data:
