name: Deploy Web Scraper on: push: branches: 
    [ main ]
jobs: build-and-deploy: runs-on: 
    ubuntu-latest
    
    steps: - uses: actions/checkout@v3
    
    - name: Set up Node.js uses: 
      actions/setup-node@v3 with:
        node-version: '18' cache: 'npm'
    
    - name: Install dependencies and build 
    frontend
      run: | cd frontend npm ci npm run build
    
    - name: Install dependencies and build 
    backend
      run: | cd backend npm ci npm run build
    
    - name: Build and push Docker images 
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub uses: 
      docker/login-action@v2 with:
        username: ${{ 
        secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN 
        }}
    
    - name: Build and push frontend image 
      uses: docker/build-push-action@v3 with:
        context: ./frontend push: true tags: 
        yourusername/webscraper-frontend:latest
    
    - name: Build and push backend image 
      uses: docker/build-push-action@v3 with:
        context: ./backend push: true tags: 
        yourusername/webscraper-backend:latest
    
    # If using a VPS or similar deployment 
    # target
    - name: Deploy to server uses: 
      appleboy/ssh-action@master with:
        host: ${{ secrets.SERVER_HOST }} 
        username: ${{ secrets.SERVER_USERNAME 
        }}
        key: ${{ secrets.SERVER_SSH_KEY }} 
        script: |
          cd /opt/webscraper docker-compose 
          pull docker-compose up -d
